services:
  db:
    image: mysql:latest
    container_name: digital_menu_mysql
    restart: unless-stopped

    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - "3306:3306"